name: Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t omgatlewar/flask-guess-game:latest .
        docker push omgatlewar/flask-guess-game:latest

    - name: Copy deployment file to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.K8S_SSH_KEY }}
        source: "k8s-deployment.yaml"
        target: "/home/${{ secrets.K8S_USER }}/"

    - name: Deploy on Kubernetes cluster via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.K8S_SSH_KEY }}
        script: |
          kubectl apply -f /home/${{ secrets.K8S_USER }}/k8s-deployment.yaml
